version: '3.8'

services:
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/:/code
      - ./backend/static:/code/static
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
