version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code
      - ./backend/static:/code/static
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
