# Generated by Django 4.2.6 on 2023-10-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePointName', models.CharField(max_length=255, verbose_name='Наименование ТТ')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес ТП')),
                ('salePointCode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код ТП')),
                ('status', models.CharField(max_length=255, verbose_name='Статус ТП')),
                ('rko', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наличие РКО')),
                ('network', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сеть')),
                ('officeType', models.CharField(blank=True, max_length=255, null=True, verbose_name='Открытый тип офиса')),
                ('salePointFormat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Формат ТП')),
                ('suoAvailability', models.CharField(blank=True, max_length=10, null=True, verbose_name='Наличие СУО')),
                ('hasRamp', models.CharField(blank=True, max_length=10, null=True, verbose_name='Флаг наличия пандуса')),
                ('latitude', models.FloatField(verbose_name='Географическая широта')),
                ('longitude', models.FloatField(verbose_name='Географическая долгота')),
                ('metroStation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Станция метро')),
                ('distance', models.IntegerField(blank=True, null=True, verbose_name='Расстояние')),
                ('kep', models.BooleanField(blank=True, null=True, verbose_name='Признак выдачи КЭП')),
                ('myBranch', models.BooleanField(blank=True, null=True, verbose_name='Признак "Мое отделение"')),
            ],
        ),
        migrations.CreateModel(
            name='OpenHoursIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50, verbose_name='День недели/Перерыв')),
                ('hours', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время')),
                ('salePoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openHoursIndividual', to='nearest_bank_api.salepoint')),
            ],
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=50, verbose_name='День недели/Перерыв')),
                ('hours', models.CharField(blank=True, max_length=50, null=True, verbose_name='Время')),
                ('salePoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openHours', to='nearest_bank_api.salepoint')),
            ],
        ),
    ]
