# Generated by Django 4.2.6 on 2023-10-14 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearest_bank_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес')),
                ('latitude', models.FloatField(verbose_name='Географическая широта')),
                ('longitude', models.FloatField(verbose_name='Географическая долгота')),
                ('allDay', models.BooleanField(default=False, verbose_name='Работает круглосуточно')),
            ],
            options={
                'verbose_name': 'Банкомат',
            },
        ),
        migrations.AlterModelOptions(
            name='openhours',
            options={'verbose_name': 'Рабочие часы для ЮЛ'},
        ),
        migrations.AlterModelOptions(
            name='openhoursindividual',
            options={'verbose_name': 'Рабочие часы для ФЛ'},
        ),
        migrations.AlterModelOptions(
            name='salepoint',
            options={'verbose_name': 'Отделение банка'},
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='AtmService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('supportsEur', 'supportsEur'), ('supportsRub', 'supportsRub'), ('supportsUsd', 'supportsUsd'), ('supportsChargeRub', 'supportsChargeRub'), ('blind', 'blind'), ('nfcForBankCards', 'nfcForBankCards'), ('qrRead', 'qrRead'), ('wheelchair', 'wheelchair')], max_length=50, verbose_name='Имя сервиса')),
                ('serviceCapability', models.CharField(choices=[('SUPPORTED', 'SUPPORTED'), ('UNKNOWN', 'UNKNOWN'), ('UNSUPPORTED', 'UNSUPPORTED')], max_length=50)),
                ('serviceActivity', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE'), ('UNKNOWN', 'UNKNOWN')], max_length=50)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='nearest_bank_api.atm')),
            ],
            options={
                'verbose_name': 'Сервис банкомата',
                'unique_together': {('atm', 'name')},
            },
        ),
    ]
