# Generated by Django 4.2.6 on 2023-10-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nearest_bank_api', '0003_atmservicethrough_salepointservicethrough_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepoint',
            name='serviceStaffAmount',
            field=models.IntegerField(default=1, verbose_name='Количество обслуживаемого персонала'),
        ),
        migrations.AddField(
            model_name='service',
            name='averageWaitTime',
            field=models.FloatField(default=1.0, verbose_name='Среднее время ожидания обслуживания на человека в минутах'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salePoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nearest_bank_api.salepoint', verbose_name='Взят для отделения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='nearest_bank_api.service', verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Талон в отделении',
            },
        ),
    ]
