# Generated by Django 4.2.6 on 2023-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearest_bank_api', '0004_salepoint_servicestaffamount_service_averagewaittiem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('Работа с Евро', 'supportsEur'), ('Работа с Рублями', 'supportsRub'), ('Работа с Долларами', 'supportsUsd'), ('Поддержка зарядки рублей', 'supportsChargeRub'), ('Услуги для слепых', 'blind'), ('Поддержка NFC для банковских карт', 'nfcForBankCards'), ('Чтение QR-кодов', 'qrRead'), ('Доступность для инвалидных колясок', 'wheelchair')], max_length=50, unique=True, verbose_name='Имя сервиса'),
        ),
    ]
