# Generated by Django 4.2.6 on 2023-10-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nearest_bank_api', '0005_alter_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmservicethrough',
            name='workload',
        ),
        migrations.RemoveField(
            model_name='salepointservicethrough',
            name='workload',
        ),
    ]
