# Generated by Django 4.2.6 on 2023-10-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nearest_bank_api', '0008_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Заметка о тикете'),
            preserve_default=False,
        ),
    ]
